version: '3.7'

services:
  app:
    build:
      context: .
    expose:
      - "5001"
    restart: always
    environment:
      - VIRTUAL_HOST=hailrake.space
    # depends_on:
    #   - "postgres"
    # networks:
    #   - aspnetcoreapp-network

    # postgres:
    #   image: postgres:latest
    #   environment:
    #     # change this for a "real" app!
    #     POSTGRES_PASSWORD: password
    #   networks:
    #     - aspnetcoreapp-network

  proxy:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - app

# networks:
#   aspnetcoreapp-network:
#     driver: bridge
